kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-fast
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880" # 48 hours
  fromBackup: ""
  diskSelector: "nvme"
  nodeSelector: "fast"
  dataLocality: "best-effort"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-large
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880" # 48 hours
  fromBackup: ""
  diskSelector: "sata"
  nodeSelector: "large"
  dataLocality: "best-effort"
