apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - longhorn/longhorn-install.yaml
  - longhorn/longhorn-config.yaml
  - metrics-server/metrics-server-install.yaml
  - coredns/coredns-config.yaml
